Elearning/Controllers/ProgressController.cs
using Elearning.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Oracle.ManagedDataAccess.Client;

namespace Elearning.Controllers
{
    public class ProgressController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ProgressView(string studentName, string courseTitle, string lessonTitle, DateTime? dateFrom, DateTime? dateTo)
        {
            //Progress progress = new Progress();
            //List<Progress> courseProgresses = progress.GetCourseProgress();
            //ViewBag.SQLData = courseProgresses;
            Progress progress = new Progress();
            List<Progress> courseProgresses = progress.GetCourseProgressFiltered(studentName, courseTitle, lessonTitle, dateFrom, dateTo);
            ViewBag.SQLData = courseProgresses;

            Student student = new Student();
            student.GetStudents();
            if (student.Students != null)
            {
                List<Student> currentStudents = new List<Student>();
                foreach (Student s in student.Students)
                {
                    if (s.Is_Deleted == 0)
                    {
                        currentStudents.Add(s);
                    }
                }
                ViewBag.Students = new SelectList(currentStudents, "Student_Id", "Student_Name");
            }

            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"];
            }
            if (TempData["ErrorMessage"] != null)
            {
                ViewBag.Message = TempData["ErrorMessage"];
            }

            return View();
        }

        public IActionResult ShowEnrolledStudents()
        {
            Enrolment enrolment = new Enrolment();
            enrolment.GetEnrolments();
            List<Enrolment> enrolments = enrolment.Enrolments;
            ViewBag.Enrolments = enrolments;

            EnrolledCourse course = new EnrolledCourse();
            List<Student> studentsEnrolled = course.GetDistinctStudents();
            ViewBag.StudentsEnrolled = new SelectList(studentsEnrolled, "Student_Id", "Student_Name");

            List<String> statusTypes = new List<String>
            {
                "Not Started", "In Progress", "Completed"
            };
            ViewBag.StatusTypes = new SelectList(statusTypes);

            return View("SearchStudent");
        }

        public IActionResult SearchCourses(int studentId)
        {
            EnrolledCourse course = new EnrolledCourse();
            List<EnrolledCourse> coursesEnrolled = course.GetEnrolledCoursesByStudentId(studentId);

            Student student = new Student();
            student.GetStudentById(studentId);
            student = student.Students[0];
            ViewBag.Student = student;

            ViewBag.SelectedStudentId = studentId;
            ViewBag.CoursesEnrolled = new SelectList(coursesEnrolled, "Course_Id", "Title");

            return View("SearchCourses");
        }

        public IActionResult AddProgress(int courseId, int studentId)
        {
            Lesson lesson = new Lesson();
            List<Lesson> courseLessons = lesson.GetLessonByCourseId(courseId);
            Console.WriteLine($"Lesson count in add lesson: {courseLessons.Count}");
            ViewBag.CourseLessons = new SelectList(courseLessons, "Lesson_Id", "Title");

            Student student = new Student();
            student.GetStudentById(studentId);
            student = student.Students[0];
            ViewBag.Student = student;

            Course course = new Course();
            course.GetCourseById(courseId);
            course = course.Courses[0];
            ViewBag.Course = course;

            List<String> statusTypes = new List<String>
            {
                "Not Started", "In Progress", "Completed"
            };
            ViewBag.StatusTypes = new SelectList(statusTypes);
            
            return View("AddProgress");
        }

        [HttpPost]
        public IActionResult AddProgressDetail(Progress courseProgress)
        {
            try
            {
                Console.WriteLine($"Course Progress in AddCourseProgress: {courseProgress.LessonStatus}");
                if (string.IsNullOrEmpty(courseProgress.StudentId.ToString())
                    || string.IsNullOrEmpty(courseProgress.LessonId.ToString())
                    || string.IsNullOrEmpty(courseProgress.LessonStatus)
                    || string.IsNullOrEmpty(courseProgress.LastAccessedDate.ToString()))
                {
                    Progress progress = new Progress();
                    List<Progress> courseProgresses = progress.GetCourseProgress();
                    ViewBag.SQLData = courseProgresses;

                    TempData["Message"] = "Empty field values";
                    return View("ProgressView");
                }
                else
                {
                    courseProgress.AddCourseProgress(courseProgress);
                    TempData["Message"] = "Course progress inserted successfully";
                    return RedirectToAction("ProgressView");
                }
            }
            catch (OracleException ex)
            {
                //TempData["ErrorMessage"] = $"An Oracle Exception occured:{ex.Message}";
                TempData["ErrorMessage"] = $"Progress for the particular course for the student already exists";
                return RedirectToAction("ProgressView");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"An error occurred: {ex.Message}";
                return RedirectToAction("ProgressView");
            }
        }

        [HttpGet]
        public ActionResult UpdateProgress(int studentId, int lessonId)
        {
            Progress courseProgress = new Progress();
            courseProgress = courseProgress.GetCourseProgressById(studentId, lessonId);
            ViewBag.SQLData = courseProgress;

            List<String> statusTypes = new List<String>
            {
                "Not Started", "In Progress", "Completed"
            };
            ViewBag.StatusTypes = new SelectList(statusTypes);

            return View("UpdateProgress", courseProgress);

        }


        [HttpPost]
        public ActionResult UpdateProgressDetail(Progress progress)
        {
            try
            {
                Progress courseProgress = new Progress();
                courseProgress.UpdateLessonProgress(progress);
                TempData["Message"] = "Course Progress updated successfully";
                return RedirectToAction("ProgressView");
            }
            catch (Exception exp)
            {
                TempData["Message"] = $"Exception occured: {exp}";
                return RedirectToAction("ProgressView");
            }
        }

        [HttpGet]
        public ActionResult DeleteProgress(int studentId, int lessonId)
        {
            Progress courseProgress = new Progress();
            courseProgress = courseProgress.GetCourseProgressById(studentId, lessonId);
            ViewBag.SQLData = courseProgress;
            return View("DeleteProgress", courseProgress);

        }

        [HttpPost]
        public ActionResult DeleteProgressDetails(int studentId, int lessonId)
        {
            try
            {
                Progress courseProgress = new Progress();
                courseProgress.DeleteCourseProgress(studentId, lessonId);
                TempData["Message"] = "Course Progress deleted successfully";
                return RedirectToAction("ProgressView");
            }
            catch (Exception exp)
            {
                TempData["Message"] = $"Exception occured: {exp}";
                return RedirectToAction("ProgressView");
            }
        }

    }
}

Elearning/Controllers/StudentController.cs
using Elearning.Models;
using Microsoft.AspNetCore.Mvc;

namespace Elearning.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult StudentView()
        {
            Student student = new Student();
            student.GetStudents();
            ViewBag.sqldata = student;

            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"];
            }
            return View();
        }

        public IActionResult ShowEnrolmentDetails(int studentId)
        {
            EnrolledCourse enrolledCourse = new EnrolledCourse();
            List<EnrolledCourse> enrolledCourses = enrolledCourse.GetEnrolledCoursesByStudentId(studentId);
            ViewBag.EnrolledCourses = enrolledCourses;

            Student student = new Student();
            student.GetStudentById(studentId);
            student = student.Students[0];
            ViewBag.StudentDetails = student;

            ViewBag.fromPage = "Students";

            return View("../Enrolment/EnrolmentDetails");
        }

        public IActionResult AddStudent()
        {
            return View("AddStudentDetail");
        }

        [HttpPost]
        public IActionResult AddStudentDetail(Student student)
        {

            Console.WriteLine($"Student ID: {student.Student_Id}");
            Console.WriteLine($"Student Name: {student.Student_Name}");
            Console.WriteLine($"Contact: {student.Contact}");
            Console.WriteLine($"DOB: {student.DOB}");
            Console.WriteLine($"Email: {student.Email}");
            Console.WriteLine($"Country: {student.Country}");
            if (string.IsNullOrEmpty(student.Student_Name)
                || string.IsNullOrEmpty(student.Contact)
                || string.IsNullOrEmpty(student.Email)
                || string.IsNullOrEmpty(student.Country))
            {
                TempData["Message"] = "Please fill all the fields before submission";
                return View(student);
            }
            else
            {
                student.AddStudent(student);
                TempData["Message"] = "Student Added Successfully";
                return RedirectToAction("StudentView");
            }
        }

        public IActionResult UpdateStudent(int studentId) 
        {
            Console.WriteLine($"In here: {studentId}");
            Student student = new Student();
            student.GetStudentById(studentId);
            Console.WriteLine(student.Students[0].Student_Name);
            ViewBag.studentData = student;
            return View("UpdateStudent", student);
        }

        [HttpPost]
        public IActionResult UpdateStudent(Student student)
        {
            if (!ModelState.IsValid)
            {
                TempData["Message"] = "Please fill all the fields before submission";
                return View(student);
            }
            else 
            {
                student.UpdateStudent(student);
                return RedirectToAction("StudentView");
            }
        }

        [HttpGet]
        public IActionResult DeleteStudent(int studentId)
        {
            Student student = new Student();
            student.GetStudentById(studentId);
            student = student.Students[0];
            ViewBag.sqldata = student;
            return View("DeleteStudent", student);
        }

        [HttpPost]
        public IActionResult DeleteStudentDetail(int studentId)
        {
            try
            {
                Student student = new Student();
                student.DeleteById(studentId);
                ViewBag.Message = $"Student deleted from the database";
                Console.WriteLine(studentId);
                TempData["Message"] = "Student deleted!";
                return RedirectToAction("StudentView");
            }
            catch (Exception exp)
            {
                TempData["Message"] = $"Error: {exp.Message}";
                return RedirectToAction("StudentView");
            }
        }
    }
}

Elearning/Views/Progress/AddProgress.cshtml
@model Elearning.Models.Progress

@{
    ViewData["Title"] = "AddLessonProgress";
    Student student = ViewBag.Student;
    Course course = ViewBag.Course;
}

<div class="row">
    <div class="container mt-4">
        <h2>Select a lesson to add progress for course @{@course.Title} for @{@student.Student_Name}</h2>
        <form asp-action="AddProgressDetail" asp-asp-controller="Progress" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-md-6">
                <label asp-for="LessonId" class="control-label">Lesson</label>
                <select asp-for="LessonId" asp-items="@ViewBag.CourseLessons" class="form-control">
                    <option value="">Select a lesson</option>
                </select>
            </div>
            <br />
            <div class="form-group col-md-6">
                <label asp-for="LastAccessedDate" class="control-label">Last Accessed Date</label>
                <input asp-for="LastAccessedDate" type="date" nameclass="form-control" />
                <span asp-validation-for="LastAccessedDate" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group col-md-6">
                <label asp-for="LessonStatus" class="control-label">Lesson Status</label>
                <select asp-for="LessonStatus" asp-items="@ViewBag.StatusTypes" class="form-control">
                    <option value="">Select a lesson</option>
                </select>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Insert" class="btn btn-primary" />
                <input type="hidden" name="StudentId" value="@student.Student_Id" />

                <a class="btn btn-danger" asp-controller="Progress" asp-action="ProgressView">Cancel</a>
            </div>

            <br />
        </form>
    </div>
</div>

Elearning/Views/Progress/DeleteProgress.cshtml
@model Elearning.Models.Progress

@{
    ViewData["Title"] = "DeleteCourseProgress";
    Progress courseProgress = new Progress();
    courseProgress = ViewBag.SQLData;
}

<h3>Are you sure you want to delete the course progress of @{
        @courseProgress.StudentName
    } to @{
        @courseProgress.CourseTitle
    } for lesson @{@courseProgress.LessonTitle}?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Student
        </dt>
        <dd class="col-sm-10">
            @courseProgress.StudentName
        </dd>
        <dt class="col-sm-2">
            Course
        </dt>
        <dd class="col-sm-10">
            @courseProgress.CourseTitle
        </dd>
        <dt class="col-sm-2">
            Lesson
        </dt>
        <dd class="col-sm-10">
            @courseProgress.LessonTitle
        </dd>
        <dt class="col-sm-2">
            Last Accessed Date
        </dt>
        <dd class="col-sm-10">
            @courseProgress.LastAccessedDate
        </dd>
    </dl>

    <form asp-action="DeleteProgressDetails" asp-controller="Progress" method="post">
        <input type="hidden" name="studentId" value="@courseProgress.StudentId" />
        <input type="hidden" name="lessonId" value="@courseProgress.LessonId" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a class="btn btn-primary" asp-action="ProgressView" asp-controller="Progress">Cancel</a>
    </form>
</div>

Elearning/Views/Progress/ProgressView.cshtml
@model Elearning.Models.Progress;

@{
    ViewData["Title"] = "ProgressView";
    var courseProgresses = ViewBag.SQLData;
}

<h1>Student Progress</h1>

<script>
    setTimeout(function () {
        document.getElementById("error-alert").style.display = "none";
    }, 1500);
    setTimeout(function () {
        document.getElementById("success-alert").style.display = "none";
    }, 1500);
</script>

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger" id="error-alert" role="alert">
        @TempData["ErrorMessage"]
    </div>
}
else if (TempData["Message"] != null)
{
    <div class="alert alert-info" id="success-alert" role="alert">
        @TempData["Message"]
    </div>
}

<form asp-action="ProgressView" method="get">
    <div class="form-group">
        <label for="studentName">Student Name:</label>
        <input type="text" class="form-control" id="studentName" name="studentName" placeholder="Enter student name">
    </div>
    <div class="form-group">
        <label for="courseTitle">Course Title:</label>
        <input type="text" class="form-control" id="courseTitle" name="courseTitle" placeholder="Enter course title">
    </div>
    <div class="form-group">
        <label for="lessonTitle">Lesson Title:</label>
        <input type="text" class="form-control" id="lessonTitle" name="lessonTitle" placeholder="Enter lesson title">
    </div>
    <div class="form-group">
        <label for="dateFrom">Date From:</label>
        <input type="date" class="form-control" id="dateFrom" name="dateFrom">
    </div>
    <div class="form-group">
        <label for="dateTo">Date To:</label>
        <input type="date" class="form-control" id="dateTo" name="dateTo">
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
</form>

<a class="btn btn-primary" asp-action="ShowEnrolledStudents">Add Progress</a><br />

@if (courseProgresses.Count > 0)
{
    <br />
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Student Name</th>
                <th>Course</th>
                <th>Lesson</th>
                <th>Last Accessed Date</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>

            @{int sn = 1;}
            @foreach (Progress c in courseProgresses)
            {
                
                <tr>
                    @* <td>@e.Student_Id</td> *@
                    @* <td>@sn</td> *@
                    <td>@c.StudentName</td>
                    <td>@c.CourseTitle</td>
                    <td>@c.LessonTitle</td>
                    <td>@c.LastAccessedDate</td>
                    <td>@c.LessonStatus</td>
                    <td>
                        <div class="btn-group gap-2">

                        <form asp-action="UpdateProgress" method="get">
                            <input type="hidden" name="studentId" value="@c.StudentId" />
                            <input type="hidden" name="lessonId" value="@c.LessonId" />
                            <button type="submit" class="btn btn-info" style="color:white">Details</button>
                        </form>
                        <form asp-action="DeleteProgress" method="get">
                            <input type="hidden" name="studentId" value="@c.StudentId" />
                            <input type="hidden" name="lessonId" value="@c.LessonId" />
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                        </div>
                    </td>
                </tr>
                sn++;
            }
        </tbody>
    </table>
}
else
{
    <h3>No CourseProgresss yet...</h3>
}

Elearning/Views/Progress/SearchCourses.cshtml
@model Elearning.Models.Progress

@{
    ViewData["Title"] = "SearchCourses";
    Student student = ViewBag.Student;
}

<div class="row">
    <div class="container mt-4">
        <h2>Select a course that @{@student.Student_Name} has enrolled on</h2>
        <form asp-action="AddProgress" asp-asp-controller="Progress" method="get">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-md-6">
                <label asp-for="CourseId" class="control-label">Course</label>
                <select asp-for="CourseId" asp-items="@ViewBag.CoursesEnrolled" class="form-control">
                    <option value="">Select a course</option>
                </select>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
                <input type="hidden" name="studentId" value="@student.Student_Id" />
                <a class="btn btn-danger" asp-controller="Progress" asp-action="ProgressView">Cancel</a>
            </div>

            <br />
        </form>
    </div>
</div>

Elearning/Views/Progress/SearchStudent.cshtml
@model Elearning.Models.Progress

@{
    ViewData["Title"] = "SearchStudent";
}

<div class="row">
    <div class="container mt-4">
        <h2>Select a student to add progress of</h2>
        <form asp-action="SearchCourses" asp-asp-controller="Progress" method="get">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-md-6">
                <label asp-for="StudentId" class="control-label">Student</label>
                <select asp-for="StudentId" asp-items="@ViewBag.StudentsEnrolled" class="form-control">
                    <option value="">Select a student</option>
                </select>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
                <a class="btn btn-danger" asp-controller="Progress" asp-action="ProgressView">Cancel</a>
            </div>

            <br />
        </form>
    </div>
</div>

Elearning/Views/Progress/UpdateProgress.cshtml
@model Elearning.Models.Progress

@{
    ViewData["Title"] = "EnrolmentDetails";

    Progress progress = ViewBag.SQLData;

}

<h1>Student Progress Details</h1>

@* @if (ViewBag.fromPage == "Enrolments")
{
    <a class="btn btn-primary" asp-action="EnrolmentView" asp-controller="Enrolment">Back to Enrolment List</a>
    <br />
}
else
{
    <a class="btn btn-primary" asp-action="StudentView" asp-controller="Student">Back to Student List</a>
    <br />
} *@

<a class="btn btn-primary" asp-action="ProgressView" asp-controller="Progress">Back to Progress List</a>
<br />

<div>
    <dl class="row">
        <dt class = "col-sm-2">
            Student Id
        </dt>
        <dd class = "col-sm-10">
            @progress.StudentId
        </dd>
        <dt class = "col-sm-2">
            Student Name
        </dt>
        <dd class = "col-sm-10">
            @progress.StudentName
        </dd>
        <dt class = "col-sm-2">
            Course
        </dt>
        <dd class = "col-sm-10">
            @progress.CourseTitle
        </dd>
        <dt class = "col-sm-2">
            Lesson
        </dt>
        <dd class = "col-sm-10">
            @progress.LessonTitle
        </dd>
        <dt class = "col-sm-2">
            Current Progress
        </dt>
        <dd class = "col-sm-10">
            @progress.LessonStatus
        </dd>
        <dt class = "col-sm-2">
            Last Accessed Date
        </dt>
        <dd class = "col-sm-10">
            @progress.LastAccessedDate
        </dd>
    </dl>
</div>

<h4>Update the lesson status</h4>
<br />
<form asp-action="UpdateProgressDetail" asp-asp-controller="Progress" method="post">

    <div class="form-group col-md-6">
        <label asp-for="LessonStatus" class="control-label">Lesson Status</label>
        <select asp-for="LessonStatus" asp-items="@ViewBag.StatusTypes" class="form-control">
            <option value="">Select a status</option>
        </select>
    </div>
    <br />
    <div class="form-group col-md-6">
        <label asp-for="LastAccessedDate" class="control-label">Accessed Date</label>
        <input asp-for="LastAccessedDate" type="date" nameclass="form-control" value="@progress.LastAccessedDate.ToString("yyyyy-MM-dd")"/>
        <span asp-validation-for="LastAccessedDate" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <input type="submit" value="Update" class="btn btn-primary" />
        <input type="hidden" name="LessonId" value="@progress.LessonId" />
        <input type="hidden" name="StudentId" value="@progress.StudentId" />

        <a class="btn btn-danger" asp-controller="Progress" asp-action="ProgressView">Cancel</a>
    </div>
</form>