Elearning/Controllers/EnrolmentController.cs
using Elearning.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Oracle.ManagedDataAccess.Client;

namespace Elearning.Controllers
{
    public class EnrolmentController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult EnrolmentView()
        {
            Enrolment enrollment = new Enrolment();
            enrollment.GetEnrolments();
            ViewBag.SQLData = enrollment;

            Student student = new Student();
            student.GetStudents();
            if (student.Students != null)
            { 
                List<Student> currentStudents = new List<Student>();
                foreach (Student s in student.Students) 
                {
                    if (s.Is_Deleted == 0)
                    { 
                        currentStudents.Add(s);
                    }
                }
                ViewBag.Students = new SelectList(currentStudents, "Student_Id", "Student_Name");
            }

            Course course = new Course();
            course.GetCourses();
            if (course.Courses != null)
            {
                List<Course> availableCourses = new List<Course> { };
                foreach (Course c in course.Courses)
                {
                    if (c.Is_Deleted == 0)
                    {
                        availableCourses.Add(c);
                    }
                }
                ViewBag.Courses = new SelectList(availableCourses, "Course_Id", "Title");
            }

            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"];
            }
            if (TempData["ErrorMessage"] != null)
            {
                ViewBag.Message = TempData["ErrorMessage"];
            }

            return View();
        }

        public IActionResult ShowEnrolmentDetails(int studentId)
        { 
            EnrolledCourse enrolledCourse = new EnrolledCourse();
            List<EnrolledCourse> enrolledCourses = enrolledCourse.GetEnrolledCoursesByStudentId(studentId);
            ViewBag.EnrolledCourses = enrolledCourses;

            Student student = new Student();
            student.GetStudentById(studentId);
            student = student.Students[0];
            ViewBag.StudentDetails = student;

            ViewBag.fromPage = "Enrolments";

            return View("EnrolmentDetails");
        }

        public IActionResult ShowCourseProgress(int studentId, int courseId)
        {
            EnrolledCourse enrolledCourse = new EnrolledCourse();
            List<EnrolledCourse> enrolledCourses = enrolledCourse.GetEnrolledCoursesByStudentId(studentId);
            ViewBag.EnrolledCourses = enrolledCourses;

            Student student = new Student();
            student.GetStudentById(studentId);
            student = student.Students[0];
            ViewBag.StudentDetails = student;

            ViewBag.fromPage = "Enrolments";

            return View("CourseProgress");
        }

        // GET: EnrolmentController/Create
        public IActionResult AddEnrolment()
        {
            Student student = new Student();
            student.GetStudents();
            if (student.Students != null)
            {
                List<Student> currentStudents = new List<Student>();
                foreach (Student s in student.Students)
                {
                    if (s.Is_Deleted == 0)
                    {
                        currentStudents.Add(s);
                    }
                }
                ViewBag.Students = new SelectList(currentStudents, "Student_Id", "Student_Name");
            }

            Course course = new Course();
            course.GetCourses();
            if (course.Courses != null)
            {
                List<Course> availableCourses = new List<Course> { };
                foreach (Course c in course.Courses)
                {
                    if (c.Is_Deleted == 0)
                    {
                        availableCourses.Add(c);
                    }
                }
                ViewBag.Courses = new SelectList(availableCourses, "Course_Id", "Title");
            }
            return View("AddEnrolmentDetail");
        }

        // POST: EnrolmentController/Create
        [HttpPost]
        public IActionResult AddEnrolmentDetail(Enrolment enrolment)
        {
            try
            {
                if (string.IsNullOrEmpty(enrolment.Student_Id.ToString()) 
                    || string.IsNullOrEmpty(enrolment.Course_Id.ToString()) 
                    || string.IsNullOrEmpty(enrolment.EnrolledOnDate.ToString()))
                {
                    TempData["Message"] = "Empty field values";
                    return View();
                }
                else
                {
                    enrolment.AddEnrolment(enrolment);
                    TempData["Message"] = "Enrolment details inserted successfully";
                    return RedirectToAction("EnrolmentView");
                }
            }
            catch (OracleException ex) when (ex.Number == 1) // Catching Oracle unique constraint error
            {
                // Handle the unique constraint violation
                TempData["ErrorMessage"] = "The student has already been enrolled in the course.";
                return RedirectToAction("EnrolmentView");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"An error occurred: {ex.Message}";
                return RedirectToAction("EnrolmentView");
            }
        }

        // GET: EnrolmentController/UpdateEnrolment/5
        public ActionResult UpdateEnrolment(int id)
        {
            return View();
        }

        // POST: EnrolmentController/UpdateEnrolment/5
        [HttpPost]
        public ActionResult UpdateEnrolment(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult DeleteEnrolment(int studentId, int courseId)
        {
            Enrolment enrolment = new Enrolment();
            enrolment = enrolment.GetEnrolmentById(studentId, courseId);
            ViewBag.SQLData = enrolment;
            return View("DeleteEnrolment", enrolment);
        }

        [HttpPost]
        public ActionResult DeleteStudentEnrolment(int studentId, int courseId)
        {
            try
            {
                Enrolment enrolment = new Enrolment();
                enrolment.DeleteEnrolment(studentId, courseId);
                TempData["Message"] = "Enrolment deleted successfully";
                return RedirectToAction("EnrolmentView");
            }
            catch (Exception exp)
            {
                TempData["Message"] = $"Exception occured: {exp}";
                return RedirectToAction("EnrolmentView");
            }
        }
    }
}

Elearning/Controllers/StudentController.cs
using Elearning.Models;
using Microsoft.AspNetCore.Mvc;

namespace Elearning.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult StudentView()
        {
            Student student = new Student();
            student.GetStudents();
            ViewBag.sqldata = student;

            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"];
            }
            return View();
        }

        public IActionResult ShowEnrolmentDetails(int studentId)
        {
            EnrolledCourse enrolledCourse = new EnrolledCourse();
            List<EnrolledCourse> enrolledCourses = enrolledCourse.GetEnrolledCoursesByStudentId(studentId);
            ViewBag.EnrolledCourses = enrolledCourses;

            Student student = new Student();
            student.GetStudentById(studentId);
            student = student.Students[0];
            ViewBag.StudentDetails = student;

            ViewBag.fromPage = "Students";

            return View("../Enrolment/EnrolmentDetails");
        }

        public IActionResult AddStudent()
        {
            return View("AddStudentDetail");
        }

        [HttpPost]
        public IActionResult AddStudentDetail(Student student)
        {

            Console.WriteLine($"Student ID: {student.Student_Id}");
            Console.WriteLine($"Student Name: {student.Student_Name}");
            Console.WriteLine($"Contact: {student.Contact}");
            Console.WriteLine($"DOB: {student.DOB}");
            Console.WriteLine($"Email: {student.Email}");
            Console.WriteLine($"Country: {student.Country}");
            if (string.IsNullOrEmpty(student.Student_Name)
                || string.IsNullOrEmpty(student.Contact)
                || string.IsNullOrEmpty(student.Email)
                || string.IsNullOrEmpty(student.Country))
            {
                TempData["Message"] = "Please fill all the fields before submission";
                return View(student);
            }
            else
            {
                student.AddStudent(student);
                TempData["Message"] = "Student Added Successfully";
                return RedirectToAction("StudentView");
            }
        }

        public IActionResult UpdateStudent(int studentId) 
        {
            Console.WriteLine($"In here: {studentId}");
            Student student = new Student();
            student.GetStudentById(studentId);
            Console.WriteLine(student.Students[0].Student_Name);
            ViewBag.studentData = student;
            return View("UpdateStudent", student);
        }

        [HttpPost]
        public IActionResult UpdateStudent(Student student)
        {
            if (!ModelState.IsValid)
            {
                TempData["Message"] = "Please fill all the fields before submission";
                return View(student);
            }
            else 
            {
                student.UpdateStudent(student);
                return RedirectToAction("StudentView");
            }
        }

        [HttpGet]
        public IActionResult DeleteStudent(int studentId)
        {
            Student student = new Student();
            student.GetStudentById(studentId);
            student = student.Students[0];
            ViewBag.sqldata = student;
            return View("DeleteStudent", student);
        }

        [HttpPost]
        public IActionResult DeleteStudentDetail(int studentId)
        {
            try
            {
                Student student = new Student();
                student.DeleteById(studentId);
                ViewBag.Message = $"Student deleted from the database";
                Console.WriteLine(studentId);
                TempData["Message"] = "Student deleted!";
                return RedirectToAction("StudentView");
            }
            catch (Exception exp)
            {
                TempData["Message"] = $"Error: {exp.Message}";
                return RedirectToAction("StudentView");
            }
        }
    }
}

Elearning/Views/Enrolment/AddEnrolmentDetail.cshtml
@model Elearning.Models.Enrolment

@{
    ViewData["Title"] = "AddEnrolmentDetail";
}

<div class="row">
    <div class="container mt-4">
        <h2>Fill the Enrolment Details Below</h2>
        <form asp-action="AddEnrolmentDetail" asp-asp-controller="Enrolment" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-md-6">
                <label asp-for="Student_Id" class="control-label">Student</label>
                <select asp-for="Student_Id" asp-items="@ViewBag.Students" class="form-control">
                    <option value="">Select a student</option>
                </select>
            </div>
            <br />
            <div class="form-group col-md-6">
                <label asp-for="Course_Id" class="control-label">Course</label>
                <select asp-for="Course_Id" asp-items="@ViewBag.Courses" class="form-control">
                    <option value="">Select a course</option>
                </select>
            </div>
            <br />
            <div class="form-group col-md-6">
                <label asp-for="EnrolledOnDate" class="control-label">Enrolment Date</label>
                <input asp-for="EnrolledOnDate" type="date" nameclass="form-control" />
                <span asp-validation-for="EnrolledOnDate" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Insert" class="btn btn-primary" />
                <a class="btn btn-danger" asp-controller="Enrolment" asp-action="EnrolmentView">Cancel</a>
            </div>

            <br />
        </form>
    </div>
</div>

Elearning/Views/Enrolment/CourseProgress.cshtml
@model IEnumerable<Elearning.Models.Course>

@{
    ViewData["Title"] = "CourseProgress";
    List<EnrolledCourse> enrolledCourses = ViewBag.EnrolledCourses;
    Student student = ViewBag.StudentDetails;
}

<h1>Progress of @{@student.Student_Name} for the course @{@enrolledCourses[0].Title}</h1>

@* <p>
    <a asp-action="Create">Create New</a>
</p> *@

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Course_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Is_Deleted)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Course_Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Is_Deleted)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Elearning/Views/Enrolment/DeleteEnrolment.cshtml
@model Elearning.Models.Enrolment

@{
    ViewData["Title"] = "DeleteEnrolment";
    Enrolment enrolment = new Enrolment();
    enrolment = ViewBag.SQLData;
}

<h3>Are you sure you want to delete the enrolment of @{
        @enrolment.Student_Name
    } to @{
        @enrolment.Course_Title
    }?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Course
        </dt>
        <dd class="col-sm-10">
            @enrolment.Course_Title
        </dd>
        <dt class="col-sm-2">
            Instructor
        </dt>
        <dd class="col-sm-10">
            @enrolment.Student_Name
        </dd>
        <dt class="col-sm-2">
            Enrolled Date
        </dt>
        <dd class="col-sm-10">
            @enrolment.EnrolledOnDate
        </dd>
    </dl>

    <form asp-action="DeleteStudentEnrolment" asp-controller="Enrolment" method="post">
        <input type="hidden" name="studentId" value="@enrolment.Student_Id" />
        <input type="hidden" name="courseId" value="@enrolment.Course_Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a class="btn btn-primary" asp-action="EnrolmentView" asp-controller="Enrolment">Cancel</a>
    </form>
</div>

Elearning/Views/Enrolment/EnrolmentDetails.cshtml
@model Elearning.Models.EnrolledCourse

@{
    ViewData["Title"] = "EnrolmentDetails";

    List<EnrolledCourse> enrolledCourses = ViewBag.EnrolledCourses;
    Student student = ViewBag.StudentDetails;
}

<h1>Student Enrolment Details</h1>

@if (ViewBag.fromPage == "Enrolments")
{
    <a class="btn btn-primary" asp-action="EnrolmentView" asp-controller="Enrolment">Back to Enrolment List</a>
    <br />
}
else
{
    <a class="btn btn-primary" asp-action="StudentView" asp-controller="Student">Back to Student List</a>
    <br />
}

<div>
    <dl class="row">
        <dt class = "col-sm-2">
            Student Id
        </dt>
        <dd class = "col-sm-10">
            @student.Student_Id
        </dd>
        <dt class = "col-sm-2">
            Name
        </dt>
        <dd class = "col-sm-10">
            @student.Student_Name
        </dd>
        <dt class = "col-sm-2">
            Contact
        </dt>
        <dd class = "col-sm-10">
            @student.Contact
        </dd>
        <dt class = "col-sm-2">
            Date Of Birth
        </dt>
        <dd class = "col-sm-10">
            @student.DOB
        </dd>
        <dt class = "col-sm-2">
            Email
        </dt>
        <dd class = "col-sm-10">
            @student.Email
        </dd>
        <dt class = "col-sm-2">
            Country
        </dt>
        <dd class = "col-sm-10">
            @student.Country
        </dd>
        <dt class="col-sm-2">
            Total Courses Enrolled On
        </dt>
        <dd class="col-sm-10">
            @enrolledCourses.Count
        </dd>
    </dl>
</div>

@if (enrolledCourses.Count > 0)
{
    <br />
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Course Id</th>
                <th>Course Title</th>
                <th>Description</th>
                <th>Enrolment Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>

            @foreach (EnrolledCourse e in enrolledCourses.Where(ec => ec.EnrolmentDeleted == 0))
            {
                <tr>
                    <td>@e.Course_Id</td>
                    <td>@e.Title</td>
                    <td>@e.Description</td>
                    <td>@e.EnrolledOnDate</td>
                    <td>
                        @* <a class="btn btn-primary" asp-action="UpdateStudent" asp-route-id="@student.Student_Id">Update</a> *@

                        <div class="btn-group gap-2">
                            <form asp-action="UpdateStudent" asp-controller="Student" method="get">
                                <input type="hidden" name="studentID" value="@student.Student_Id" />
                                <input type="submit" value="Update" class="btn btn-primary" />
                            </form>

                            <form asp-action="EnrolmentDetails" method="get">
                                <input type="hidden" name="studentId" value="@student.Student_Id" />
                                <input type="hidden" name="courseId" value="@e.Course_Id" />
                                <button type="submit" class="btn btn-info" style="color:white">Details</button>
                            </form>

                            <form asp-action="DeleteStudent" method="get">
                                <input type="hidden" name="studentId" value="@student.Student_Id" />
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h3>Student has not enrolled in any courses yet...</h3>
}

Elearning/Views/Enrolment/EnrolmentView.cshtml
@model Elearning.Models.Enrolment;

@{
    ViewData["Title"] = "EnrolmentView";
    Enrolment enrolment = ViewBag.SQLData;
}

<h1>Enrolments</h1>

@* <p>
    <a asp-action="Create">Create New</a>
</p> *@

<script>
    // Hide alert after 3 seconds
    setTimeout(function () {
        document.getElementById("error-alert").style.display = "none";
    }, 1500);
    setTimeout(function () {
        document.getElementById("success-alert").style.display = "none";
    }, 1500);
</script>

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger" id="error-alert" role="alert">
        @TempData["ErrorMessage"]
    </div>
}
else if (TempData["Message"] != null)
{
    <div class="alert alert-info" id="success-alert" role="alert">
        @TempData["Message"]
    </div>
}


@* <div class="container mt-4">
    <h2>Fill the Enrolment Details Below</h2>
    <form asp-action="AddEnrolment" asp-asp-controller="Enrolment" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group col-md-6">
            <label asp-for="Student_Id" class="control-label">Student</label>
            <select asp-for="Student_Id" asp-items="@ViewBag.Students" class="form-control">
                <option value="">Select a student</option>
            </select>
        </div>
        <br />
        <div class="form-group col-md-6">
            <label asp-for="Course_Id" class="control-label">Course</label>
            <select asp-for="Course_Id" asp-items="@ViewBag.Courses" class="form-control">
                <option value="">Select a course</option>
            </select>
        </div>
        <br />
        <div class="form-group col-md-6">
            <label asp-for="EnrolledOnDate" class="control-label">Enrolment Date</label>
            <input asp-for="EnrolledOnDate" type="date" nameclass="form-control" />
            <span asp-validation-for="EnrolledOnDate" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" value="Add" class="btn btn-primary" />
            <input type="reset" value="Cancel" class="btn btn-secondary" />
        </div>

        <br />
    </form>
</div> *@


<a class="btn btn-primary" asp-action="AddEnrolment">Add Enrolment</a><br />

@if (enrolment.Enrolments.Count > 0)
{
    <br />
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                @* <th>Student Id</th> *@
                <th>S.N.</th>
                <th>Course Id</th>
                <th>Student</th>
                <th>Course</th>
                <th>Enrolment Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>

            @{int sn = 1;}
            @foreach (Enrolment e in enrolment.Enrolments.Where(en => en.Is_Deleted == 0))
            {
                
                <tr>
                    @* <td>@e.Student_Id</td> *@
                    <td>@sn</td>
                    <td>@e.Course_Id</td>
                    <td>@e.Student_Name</td>
                    <td>@e.Course_Title</td>
                    <td>@e.EnrolledOnDate</td>
                    <td>
                        @* <a class="btn btn-primary" asp-action="UpdateEnrolment" asp-route-id="@e.Enrollment_Id">Update</a> *@
                        @* <form asp-action="UpdateEnrolment" asp-controller="Enrolment" method="get">
                            <input type="hidden" name="Student_Id" value="@e.Student_Id" />
                            <input type="hidden" name="Course_Id" value="@e.Course_Id" />
                            <input type="submit" value="Update" class="btn btn-primary" />
                        </form> *@
                        <div class="btn-group gap-2">

                        <form asp-action="ShowEnrolmentDetails" method="get">
                            <input type="hidden" name="studentId" value="@e.Student_Id" />
                            <input type="hidden" name="courseId" value="@e.Course_Id" />
                            <button type="submit" class="btn btn-info" style="color:white">Details</button>
                        </form>
                        <form asp-action="DeleteEnrolment" method="get">
                            <input type="hidden" name="studentId" value="@e.Student_Id" />
                            <input type="hidden" name="courseId" value="@e.Course_Id" />
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                        </div>
                    </td>
                </tr>
                sn++;
            }
        </tbody>
    </table>
}
else
{
    <h3>No Enrolments yet...</h3>
}