Elearning/Models/InstructorAssignment.cs
using Elearning.Utilities;
using Oracle.ManagedDataAccess.Client;

namespace Elearning.Models
{
    public class InstructorAssignment
    {
        public int Course_Id { get; set; }

        public string Course_Title { get; set; }

        public int Instructor_Id { get; set; }
        public string Instructor_Name { get; set; }
        public int Is_Deleted { get; set; }

        public DateTime AssignedDate { get; set; }

        public List<InstructorAssignment> Assignments = new List<InstructorAssignment>();

        public string connString = ProjectConstants.connString;

        public void AddInstructorAssignment(InstructorAssignment assignment)
        {
            try
            {
                using (OracleConnection conn = new OracleConnection(connString))
                {
                    string queryString = "INSERT INTO INSTRUCTOR_ASSIGNMENT (COURSE_ID, INSTRUCTOR_ID, ASSIGNED_DATE) " +
                                         "VALUES(:COURSE_ID, :INSTRUCTOR_ID, TO_DATE(:ASSIGNED_DATE, 'YYYY-MM-DD'))";

                    OracleCommand cmd = new OracleCommand(queryString, conn);
                    cmd.Parameters.Add(new OracleParameter("COURSE_ID", assignment.Course_Id));
                    cmd.Parameters.Add(new OracleParameter("INSTRUCTOR_ID", assignment.Instructor_Id));
                    cmd.Parameters.Add(new OracleParameter("ASSIGNED_DATE", assignment.AssignedDate.ToString("yyyy-MM-dd")));

                    conn.Open();
                    cmd.ExecuteNonQuery();
                    conn.Close();
                }
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception.Message);
                throw;
            }
        }

        public void GetInstructorAssignments()
        {
            try
            {
                using (OracleConnection conn = new OracleConnection(connString))
                {
                    string query = "SELECT c.COURSE_ID, c.TITLE, i.INSTRUCTOR_ID, i.NAME, ia.ASSIGNED_DATE FROM INSTRUCTOR_ASSIGNMENT ia " +
                                   "JOIN COURSE c ON ia.COURSE_ID = c.COURSE_ID JOIN INSTRUCTOR i ON ia.INSTRUCTOR_ID = i.INSTRUCTOR_ID";
                    OracleCommand cmd = new OracleCommand(query, conn);
                    cmd.BindByName = true;
                    cmd.CommandType = System.Data.CommandType.Text;

                    conn.Open();
                    OracleDataReader reader = cmd.ExecuteReader();
                    while (reader.Read())
                    {
                        InstructorAssignment assignment = new InstructorAssignment
                        {
                            
                            Course_Id = reader.GetInt32(0),
                            Course_Title = reader.GetString(1),
                            Instructor_Id = reader.GetInt32(2),
                            Instructor_Name = reader.GetString(3),
                            AssignedDate = reader.GetDateTime(4)
                        };
                        Assignments.Add(assignment);
                    }
                    reader.Dispose();
                    conn.Close();
                }
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception.Message);
                throw;
            }
        }

        public InstructorAssignment GetInstructorAssignmentById(int courseId, int instructorId)
        {
            try
            {
                using (OracleConnection conn = new OracleConnection(connString))
                {
                    string query = $"SELECT c.COURSE_ID, c.TITLE, i.INSTRUCTOR_ID, i.NAME, ia.ASSIGNED_DATE FROM INSTRUCTOR_ASSIGNMENT ia " +
                                   $"JOIN COURSE c ON ia.COURSE_ID = c.COURSE_ID JOIN INSTRUCTOR i ON ia.INSTRUCTOR_ID = i.INSTRUCTOR_ID " +
                                   $"WHERE ia.COURSE_ID = {courseId} AND ia.INSTRUCTOR_ID = {instructorId}";
                    OracleCommand cmd = new OracleCommand(query, conn);
                    cmd.BindByName = true;
                    cmd.CommandType = System.Data.CommandType.Text;

                    conn.Open();
                    OracleDataReader reader = cmd.ExecuteReader();
                    InstructorAssignment assignment = new InstructorAssignment();
                    while (reader.Read())
                    {
                        assignment.Course_Id = reader.GetInt32(0);
                        assignment.Course_Title = reader.GetString(1);
                        assignment.Instructor_Id = reader.GetInt32(2);
                        assignment.Instructor_Name = reader.GetString(3);
                        assignment.AssignedDate = reader.GetDateTime(4);
                    }
                    reader.Dispose();
                    conn.Close();
                    return assignment;
                }
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception.Message);
                throw;
            }
        }

        public List<InstructorAssignment> GetInstructorsForCourse(int courseId)
        {
            try
            {
                using (OracleConnection conn = new OracleConnection(connString))
                {
                    string query = $"SELECT c.COURSE_ID, c.TITLE, i.INSTRUCTOR_ID, i.NAME, ia.ASSIGNED_DATE FROM INSTRUCTOR_ASSIGNMENT ia " +
                                   $"JOIN COURSE c ON ia.COURSE_ID = c.COURSE_ID JOIN INSTRUCTOR i ON ia.INSTRUCTOR_ID = i.INSTRUCTOR_ID " +
                                   $"WHERE ia.COURSE_ID = {courseId} " +
                                   $"AND (SELECT COUNT(INSTRUCTOR_ID) FROM INSTRUCTOR_ASSIGNMENT WHERE INSTRUCTOR_ID = ia.INSTRUCTOR_ID) >= 2";
                    OracleCommand cmd = new OracleCommand(query, conn);
                    cmd.BindByName = true;
                    cmd.CommandType = System.Data.CommandType.Text;

                    conn.Open();
                    OracleDataReader reader = cmd.ExecuteReader();
                    List<InstructorAssignment> assignments = new List<InstructorAssignment>();
                    while (reader.Read())
                    {
                        InstructorAssignment assignment = new InstructorAssignment();
                        assignment.Course_Id = reader.GetInt32(0);
                        assignment.Course_Title = reader.GetString(1);
                        assignment.Instructor_Id = reader.GetInt32(2);
                        assignment.Instructor_Name = reader.GetString(3);
                        assignment.AssignedDate = reader.GetDateTime(4);
                        assignments.Add(assignment);
                    }
                    reader.Dispose();
                    conn.Close();
                    return assignments;
                }
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception.Message);
                throw;
            }
        }

        public void DeleteAssignment(int courseId, int instructorId)
        {
            try
            {
                using (OracleConnection conn = new OracleConnection(connString))
                {
                    string queryString = "DELETE FROM INSTRUCTOR_ASSIGNMENT WHERE COURSE_ID = :COURSE_ID AND INSTRUCTOR_ID = :INSTRUCTOR_ID";

                    OracleCommand cmd = new OracleCommand(queryString, conn);
                    cmd.Parameters.Add(new OracleParameter("COURSE_ID", courseId));
                    cmd.Parameters.Add(new OracleParameter("INSTRUCTOR_ID", instructorId));

                    conn.Open();
                    cmd.ExecuteNonQuery();
                    conn.Close();
                }
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception.Message);
                throw;
            }
        }
    }
}

Elearning/Controllers/InstructorAssignmentController.cs
using Elearning.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Oracle.ManagedDataAccess.Client;

namespace Elearning.Controllers
{
    public class InstructorAssignmentController : Controller
    {
        // GET: InstructorAssignmentController
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult InstructorAssignmentView()
        {
            InstructorAssignment instructorAssignment = new InstructorAssignment();
            instructorAssignment.GetInstructorAssignments();
            ViewBag.SQLData = instructorAssignment;

            Instructor instructor = new Instructor();
            instructor.GetInstructors();
            if (instructor.Instructors != null)
            {
                List<Instructor> availableInstructors = new List<Instructor> { };
                foreach (Instructor i in instructor.Instructors)
                {
                    if (i.IsDeleted == 0)
                    {
                        availableInstructors.Add(i);
                    }
                }
                ViewBag.InstructorList = new SelectList(availableInstructors, "InstructorId", "Name");
            }

            Course course = new Course();
            course.GetCourses();
            if (course.Courses != null)
            {
                List<Course> availableCourses = new List<Course> { };
                foreach (Course c in course.Courses)
                {
                    if (c.Is_Deleted == 0)
                    {
                        availableCourses.Add(c);
                    }
                }
                ViewBag.CourseList = new SelectList(availableCourses, "Course_Id", "Title");
            }
            
            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"];
            }
            if (TempData["ErrorMessage"] != null)
            {
                ViewBag.Message = TempData["ErrorMessage"];
            }

            return View();
        }

        [HttpGet]
        public IActionResult AssignInstructor()
        {
            Instructor instructor = new Instructor();
            instructor.GetInstructors();
            if (instructor.Instructors != null)
            {
                List<Instructor> availableInstructors = new List<Instructor> { };
                foreach (Instructor i in instructor.Instructors)
                {
                    if (i.IsDeleted == 0)
                    {
                        availableInstructors.Add(i);
                    }
                }
                ViewBag.Instructors = new SelectList(availableInstructors, "InstructorId", "Name");
            }

            Course course = new Course();
            course.GetCourses();
            if (course.Courses != null)
            {
                List<Course> availableCourses = new List<Course> { };
                foreach (Course c in course.Courses)
                {
                    if (c.Is_Deleted == 0)
                    {
                        availableCourses.Add(c);
                    }
                }
                ViewBag.Courses = new SelectList(availableCourses, "Course_Id", "Title");
            }


            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"];
            }
            Console.WriteLine("In AssignInstructor");

            return View("AddInstructorAssignment");
        }

        [HttpPost]
        public IActionResult AddAssignmentDetails(InstructorAssignment assignment)
        {
            try
            {
                if (string.IsNullOrEmpty(assignment.Course_Id.ToString())
                    || string.IsNullOrEmpty(assignment.Instructor_Id.ToString())
                    || string.IsNullOrEmpty(assignment.AssignedDate.ToString()))
                {
                    TempData["ErrorMessage"] = "Empty field values";
                    return View();
                }
                else
                {
                    assignment.AddInstructorAssignment(assignment);
                    TempData["Message"] = "Assignment details inserted successfully";
                    return RedirectToAction("InstructorAssignmentView");
                }
            }
            catch (OracleException ex) when (ex.Number == 1)
            {
                TempData["ErrorMessage"] = "The instructor has already been assigned to the course.";
                return RedirectToAction("InstructorAssignmentView");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"An error occurred: {ex.Message}";
                return RedirectToAction("InstructorAssignmentView");
            }
        }

        [HttpGet]
        public ActionResult DeleteAssignment(int courseId, int instructorId)
        {
            InstructorAssignment assignment = new InstructorAssignment();
            assignment = assignment.GetInstructorAssignmentById(courseId, instructorId);
            ViewBag.SQLData = assignment;
            return View("DeleteInstructorAssignment", assignment);
        }

        // POST: EnrolmentController/Delete/5
        [HttpPost]
        public ActionResult DeleteInstructorAssignment(int courseId, int instructorId)
        {
            try
            {
                InstructorAssignment enrolment = new InstructorAssignment();
                enrolment.DeleteAssignment(courseId, instructorId);
                TempData["Message"] = "Instructor Assignment deleted successfully";
                return RedirectToAction("InstructorAssignmentView");
            }
            catch (Exception exp)
            {
                TempData["Message"] = $"Exception occured: {exp}";
                return RedirectToAction("InstructorAssignmentView");
            }
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: InstructorAssignmentController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InstructorAssignmentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InstructorAssignmentController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: InstructorAssignmentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InstructorAssignmentController/Delete/5
        
    }
}

Elearning/Views/InstructorAssignment/AddInstructorAssignment.cshtml
@model Elearning.Models.InstructorAssignment

@{
    ViewData["Title"] = "AddAssignmentDetail";
}

<div class="row">
    <div class="container mt-4">
        <h2>Fill the Enrolment Details Below</h2>
        <form asp-action="AddAssignmentDetails" asp-asp-controller="InstructorAssignmentController" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-md-6">
                <label asp-for="Course_Id" class="control-label">Course</label>
                <select asp-for="Course_Id" asp-items="@ViewBag.Courses" class="form-control">
                    <option value="">Select a Course</option>
                </select>
            </div>
            <br />
            <div class="form-group col-md-6">
                <label asp-for="Instructor_Id" class="control-label">Instructor</label>
                <select asp-for="Instructor_Id" asp-items="@ViewBag.Instructors" class="form-control">
                    <option value="">Select a Instructor</option>
                </select>
            </div>
            <br />
            <div class="form-group col-md-6">
                <label asp-for="AssignedDate" class="control-label">Assignment Date</label>
                <input asp-for="AssignedDate" type="date" nameclass="form-control" />
                <span asp-validation-for="AssignedDate" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Insert" class="btn btn-primary" />
                <a class="btn btn-danger" asp-controller="InstructorAssignment" asp-action="InstructorAssignmentView">Cancel</a>
            </div>

            <br />
        </form>
    </div>
</div>

Elearning/Views/InstructorAssignment/DeleteInstructorAssignment.cshtml
@model Elearning.Models.InstructorAssignment

@{
    ViewData["Title"] = "DeleteInstructorAssignment";
    InstructorAssignment assignment = new InstructorAssignment();
    assignment = ViewBag.SQLData;
}

<h3>Are you sure you want to delete the assignment of @{@assignment.Instructor_Name} to @{@assignment.Course_Title}?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Course
        </dt>
        <dd class="col-sm-10">
            @assignment.Course_Title
        </dd>
        <dt class="col-sm-2">
            Instructor
        </dt>
        <dd class="col-sm-10">
            @assignment.Instructor_Name
        </dd>
        <dt class="col-sm-2">
            Assigned Date
        </dt>
        <dd class="col-sm-10">
            @assignment.AssignedDate
        </dd>
    </dl>

    <form asp-action="DeleteInstructorAssignment" asp-controller="InstructorAssignment" method="post">
        <input type="hidden" name="courseId" value="@assignment.Course_Id" />
        <input type="hidden" name="instructorId" value="@assignment.Instructor_Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a class="btn btn-primary" asp-action="InstuctorAssignmentView" asp-controller="InstructorAssignment">Cancel</a>
    </form>
</div>

Elearning/Views/InstructorAssignment/InstructorAssignmentView.cshtml
@model Elearning.Models.InstructorAssignment

@{
    InstructorAssignment assignmentSQLData = ViewBag.SQLData;
}

<h1>Instructor Assignment View</h1>

<script>
    setTimeout(function () {
        document.getElementById("error-alert").style.display = "none";
    }, 1500);
    setTimeout(function () {
        document.getElementById("success-alert").style.display = "none";
    }, 1500);
</script>

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger" id="error-alert" role="alert">
        @TempData["ErrorMessage"]
    </div>
}
else if (TempData["Message"] != null)
{
    <div class="alert alert-info" id="success-alert" role="alert">
        @TempData["Message"]
    </div>
}

<p>
    <a asp-action="Create">Create New</a>
</p>

<a class="btn btn-primary" asp-action="AssignInstructor" asp-controller="InstructorAssignment">Add Assignment</a>


@if (assignmentSQLData.Assignments.Count > 0)
{
    <br />
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Course Id</th>
                <th>Instructor Id</th>
                <th>Course Title</th>
                <th>Instructor Name</th>
                <th>Assigned Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (InstructorAssignment assignment in assignmentSQLData.Assignments.Where(en => en.Is_Deleted == 0))
            {
                <tr>
                    <td>@assignment.Course_Id</td>
                    <td>@assignment.Instructor_Id</td>
                    <td>@assignment.Course_Title</td>
                    <td>@assignment.Instructor_Name</td>
                    <td>@assignment.AssignedDate</td>
                    <td>
                        @* <a class="btn btn-primary" asp-action="UpdateInstructorAssignment" asp-route-id="@assignment.Enrollment_Id">Update</a> *@
                        @* <form asp-action="UpdateInstructorAssignment" asp-controller="InstructorAssignment" method="get">
                <input type="hidden" name="Student_Id" value="@assignment.Student_Id" />
                <input type="hidden" name="Course_Id" value="@assignment.Course_Id" />
                <input type="submit" value="Update" class="btn btn-primary" />
                </form> *@
                        <form asp-action="DeleteAssignment" asp-controller="InstructorAssignment" method="get">
                            <input type="hidden" name="courseId" value="@assignment.Course_Id" />
                            <input type="hidden" name="instructorId" value="@assignment.Instructor_Id" />
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h3>No Instructor Assignments yet...</h3>
}