Elearning/Controllers/LessonController.cs
using System.Diagnostics;
using Elearning.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Elearning.Controllers
{
    public class LessonController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult LessonView()
        {
            Lesson lesson = new Lesson();
            lesson.GetLessons();
            ViewBag.SQLData = lesson;

            Course course = new Course();
            course.GetCourses();
            if (course.Courses != null)
            {
                List<Course> availableCourses = new List<Course> { };
                foreach (Course c in course.Courses)
                {
                    if (c.Is_Deleted == 0)
                    {
                        availableCourses.Add(c);
                    }
                }
                ViewBag.CourseList = new SelectList(availableCourses, "Course_Id", "Title");
            }

            List<String> lessonTypes = new List<String> 
            { 
                "PDF", "Video", "Link"
            };
            ViewBag.LessonTypes = new SelectList(lessonTypes, "LessonType");

            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"];
            }

            return View();
        }

        public IActionResult Details(int id)
        {
            return View();
        }

        public IActionResult AddLesson(Lesson lesson)
        {
            Course course = new Course();
            course.GetCourses();
            if (course.Courses != null)
            {
                List<Course> availableCourses = new List<Course> { };
                foreach (Course c in course.Courses)
                {
                    if (c.Is_Deleted == 0)
                    {
                        availableCourses.Add(c);
                    }
                }
                ViewBag.CourseList = new SelectList(availableCourses, "Course_Id", "Title");
            }

            List<String> lessonTypes = new List<String>
            {
                "PDF", "Video", "Link"
            };
            ViewBag.LessonTypes = new SelectList(lessonTypes, "LessonType");
            return View("AddLessonDetail");
        }
        
        [HttpPost]
        public IActionResult AddLessonDetail(Lesson lesson)
        {
            if (string.IsNullOrEmpty(lesson.Title) || string.IsNullOrEmpty(lesson.Course_Id.ToString()))
            {
                TempData["Message"] = "Empty field values";
                return View();
            }
            else
            {
                lesson.AddLesson(lesson);
                ViewBag.Message = "Lesson details added";
                TempData["Message"] = "Lesson details inserted successfully";
                return RedirectToAction("LessonView");
            }
        }

        public IActionResult UpdateLesson(int id)
        {
            Lesson lesson = new();
            lesson = lesson.GetLessonByLessonId(id);
            ViewBag.SQLData = lesson;

            Course course = new Course();
            course.GetCourses();
            if (course.Courses != null)
            {
                List<Course> availableCourses = new List<Course> { };
                foreach (Course c in course.Courses)
                {
                    if (c.Is_Deleted == 0)
                    {
                        availableCourses.Add(c);
                    }
                }
                ViewBag.CourseList = new SelectList(availableCourses, "Course_Id", "Title");
            }
            List<String> lessonTypes = new List<String>
            {
                "PDF", "Video", "Link"
            };
            ViewBag.LessonTypes = new SelectList(lessonTypes, "LessonType");
            return View("UpdateLesson", lesson);
        }

        [HttpPost]
        public IActionResult UpdateLesson(Lesson lesson)
        {
            try
            {
                if (string.IsNullOrEmpty(lesson.Title) || string.IsNullOrEmpty(lesson.Course_Id.ToString()))
                {
                    TempData["Message"] = "Empty fields submitted";
                    return RedirectToAction("LessonView");
                }
                else
                {
                    Lesson updatedLesson = new Lesson();
                    updatedLesson.Title = lesson.Title;
                    updatedLesson.Course_Id = lesson.Course_Id;
                    Console.WriteLine(lesson.Title);
                    Console.WriteLine(lesson.Course_Id);
                    updatedLesson.UpdateLesson(lesson);
                    TempData["Message"] = $"Lesson: {lesson.Title} updated successfully";
                    return RedirectToAction("LessonView");
                }
            }
            catch (Exception exp)
            {
                TempData["Message"] = $"Error: {exp.Message}";
                return RedirectToAction("LessonView");
            }
        }

        [HttpGet]
        public IActionResult DeleteLesson(int id)
        {
            Lesson lesson = new();
            lesson = lesson.GetLessonByLessonId(id);
            ViewBag.SQLData = lesson;
            return View("DeleteLesson", lesson);
        }

        [HttpPost]
        public IActionResult DeleteLessonDetail(int id)
        {
            try
            {
                Console.WriteLine($"del: {id}");
                Lesson newLesson = new Lesson();
                newLesson.DeleteLesson(id);
                ViewBag.Message = $"Lesson deleted from the database";
                Console.WriteLine(id);
                TempData["Message"] = $"Lesson with id {id} deleted!";
                return RedirectToAction("LessonView");
            }
            catch (Exception exp)
            {
                TempData["Message"] = $"Error: {exp.Message}";
                return RedirectToAction("LessonView");
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Elearning/Controllers/StudentController.cs
using Elearning.Models;
using Microsoft.AspNetCore.Mvc;

namespace Elearning.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult StudentView()
        {
            Student student = new Student();
            student.GetStudents();
            ViewBag.sqldata = student;

            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"];
            }
            return View();
        }

        public IActionResult ShowEnrolmentDetails(int studentId)
        {
            EnrolledCourse enrolledCourse = new EnrolledCourse();
            List<EnrolledCourse> enrolledCourses = enrolledCourse.GetEnrolledCoursesByStudentId(studentId);
            ViewBag.EnrolledCourses = enrolledCourses;

            Student student = new Student();
            student.GetStudentById(studentId);
            student = student.Students[0];
            ViewBag.StudentDetails = student;

            ViewBag.fromPage = "Students";

            return View("../Enrolment/EnrolmentDetails");
        }

        public IActionResult AddStudent()
        {
            return View("AddStudentDetail");
        }

        [HttpPost]
        public IActionResult AddStudentDetail(Student student)
        {

            Console.WriteLine($"Student ID: {student.Student_Id}");
            Console.WriteLine($"Student Name: {student.Student_Name}");
            Console.WriteLine($"Contact: {student.Contact}");
            Console.WriteLine($"DOB: {student.DOB}");
            Console.WriteLine($"Email: {student.Email}");
            Console.WriteLine($"Country: {student.Country}");
            if (string.IsNullOrEmpty(student.Student_Name)
                || string.IsNullOrEmpty(student.Contact)
                || string.IsNullOrEmpty(student.Email)
                || string.IsNullOrEmpty(student.Country))
            {
                TempData["Message"] = "Please fill all the fields before submission";
                return View(student);
            }
            else
            {
                student.AddStudent(student);
                TempData["Message"] = "Student Added Successfully";
                return RedirectToAction("StudentView");
            }
        }

        public IActionResult UpdateStudent(int studentId) 
        {
            Console.WriteLine($"In here: {studentId}");
            Student student = new Student();
            student.GetStudentById(studentId);
            Console.WriteLine(student.Students[0].Student_Name);
            ViewBag.studentData = student;
            return View("UpdateStudent", student);
        }

        [HttpPost]
        public IActionResult UpdateStudent(Student student)
        {
            if (!ModelState.IsValid)
            {
                TempData["Message"] = "Please fill all the fields before submission";
                return View(student);
            }
            else 
            {
                student.UpdateStudent(student);
                return RedirectToAction("StudentView");
            }
        }

        [HttpGet]
        public IActionResult DeleteStudent(int studentId)
        {
            Student student = new Student();
            student.GetStudentById(studentId);
            student = student.Students[0];
            ViewBag.sqldata = student;
            return View("DeleteStudent", student);
        }

        [HttpPost]
        public IActionResult DeleteStudentDetail(int studentId)
        {
            try
            {
                Student student = new Student();
                student.DeleteById(studentId);
                ViewBag.Message = $"Student deleted from the database";
                Console.WriteLine(studentId);
                TempData["Message"] = "Student deleted!";
                return RedirectToAction("StudentView");
            }
            catch (Exception exp)
            {
                TempData["Message"] = $"Error: {exp.Message}";
                return RedirectToAction("StudentView");
            }
        }
    }
}

Elearning/Views/Lesson/AddLessonDetail.cshtml
@model Elearning.Models.Lesson

@{
    ViewData["Title"] = "AddLessonDetail";
}

<div class="container mt-4">
    <h2>Fill the Lesson Details Below</h2>
    <form asp-action="AddLessonDetail" asp-asp-controller="Lesson" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group col-md-6">
            <label asp-for="Title" class="control-label">Lesson Title</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <br />
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Course_Id" class="control-label">Course</label>
                <select asp-for="Course_Id" asp-items="@ViewBag.CourseList" class="form-control">
                    <option value="">Please select a course</option>
                </select>
            </div>
            <br />
            <div class="form-group col-md-6">
                <label asp-for="Content_Name" class="control-label">Content Name</label>
                <input asp-for="Content_Name" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group col-md-6">
                <label asp-for="Content_Type" class="control-label">Lesson Type</label>
                <select asp-for="Content_Type" asp-items="@ViewBag.LessonTypes" class="form-control">
                    <option value="">Please select a lesson type</option>
                </select>
            </div>

        </div>

        <br />
        <div class="form-group">
            <input type="submit" value="Insert" class="btn btn-primary" />
            <a class="btn btn-danger" asp-controller="Lesson" asp-action="LessonView">Cancel</a>
        </div>
        <br />
        
    </form>
</div>

Elearning/Views/Lesson/DeleteLesson.cshtml
@model Elearning.Models.Lesson

@{
    ViewData["Title"] = "DeleteLesson";
    Lesson lesson = new Lesson();
    lesson = ViewBag.SQLData;
}

<h3>
    Are you sure you want to delete the lesson @{
        @lesson.Title
    } from @{
        @lesson.Course_Title
    }?
</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Lesson
        </dt>
        <dd class="col-sm-10">
            @lesson.Title
        </dd>
        <dt class="col-sm-2">
            Course
        </dt>
        <dd class="col-sm-10">
            @lesson.Course_Title
        </dd>
        <dt class="col-sm-2">
            Lesson Content
        </dt>
        <dd class="col-sm-10">
            @lesson.Content_Name
        </dd>
    </dl>

    <form asp-action="DeleteLessonDetail" asp-controller="Lesson" method="post">
        <input type="hidden" name="id" value="@lesson.Lesson_Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a class="btn btn-primary" asp-action="LessonView" asp-controller="Lesson">Cancel</a>
    </form>
</div>

Elearning/Views/Lesson/LessonView.cshtml
@model Elearning.Models.Lesson;

@{
    ViewData["Title"] = "LessonView";
    Lesson lesson = ViewBag.SQLData;
}

<h1>Lessons</h1>

<script>
    setTimeout(function () {
        document.getElementById("alert").style.display = "none";
    }, 1500);
</script>

@if (ViewBag.Message != null)
{
    <div class="alert alert-info" id="alert" role="alert">
        @ViewBag.Message
    </div>
}

@* <div class="container mt-4">
    <h2>Fill the Lesson Details Below</h2>
    <form asp-action="AddLesson" asp-asp-controller="Lesson" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-md-6">
                <label asp-for="Title" class="control-label">Lesson Title</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <br />
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="Course_Id" class="control-label">Course</label>
                    <select asp-for="Course_Id" asp-items="@ViewBag.CourseList" class="form-control">
                        <option value="">Please select a course</option>
                    </select>
                </div>
            <br />
                <div class="form-group col-md-6">
                    <label asp-for="Content_Name" class="control-label">Content Name</label>
                    <input asp-for="Content_Name" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group col-md-6">
                    <label asp-for="Content_Type" class="control-label">Lesson Type</label>
                    <select asp-for="Content_Type" asp-items="@ViewBag.LessonTypes" class="form-control">
                        <option value="">Please select a lesson type</option>
                    </select>
                </div>

            </div>
            
            <br />
            <div class="form-group">
                <input type="submit" value="Insert" class="btn btn-primary" />
                <input type="reset" value="Cancel" class="btn btn-secondary" />
            </div>
        
        <br />
    </form>
</div> *@

<a class="btn btn-primary" asp-controller="Lesson" asp-action="AddLesson">Add Lesson</a>
<br />

@if (lesson.Lessons.Count > 0)
{
    <br />
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Lesson ID</th>
                <th>Lesson Title</th>
                <th>Course Title</th>
                <th>Lesson Content</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>

            @foreach (Lesson l in lesson.Lessons.Where(l => l.Is_Deleted == 0))
            {
                Console.WriteLine(l.Lesson_Id);
                <tr>
                    <td>@l.Lesson_Id</td>
                    <td>@l.Title</td>
                    <td>@l.Course_Title</td>
                    <td>@l.Content_Name</td>
                    <td>
                        @* <a class="btn btn-primary" asp-action="UpdateLesson" asp-route-id="@l.Lesson_Id">Update</a> *@
                        <div class="form-group">
                            @* <input type="submit" value="Insert" class="btn btn-primary" />
                            <a class="btn btn-danger" asp-controller="Student" asp-action="StudentView">Cancel</a> *@
                            <form asp-action="UpdateLesson" asp-controller="Lesson" method="get">
                                <input type="hidden" name="id" value="@l.Lesson_Id" />
                                <input type="submit" value="Update" class="btn btn-primary" />
                            </form>
                            @{
                                Console.WriteLine($"In here: {l.Lesson_Id}");
                            }
                            <form asp-action="DeleteLesson" asp-route-id="@l.Lesson_Id" method="get">
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </div>
                       
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h3>No Details of students...</h3>
}

Elearning/Views/Lesson/UpdateLesson.cshtml
@using Elearning.Models
@model Lesson
@{
    ViewData["text"] = ViewBag.Message;
    Lesson lesson = ViewBag.SQLData;

    // List<Course> courses = ViewBag.CourseList;
    // Course course = new Course();

    // foreach (Course c in courses)
    // {
    //     if (c.Course_Id == lesson.Course_Id)
    //     {
    //         course = c;
    //     }
    // }

    string content_name = lesson.Content_Name.Split('.')[0];
    string lesson_type = lesson.Content_Name.Split('.')[1];
}

<div class="flex-column">
    <div class="align-content-center">
        <form method="post" asp-action="UpdateLesson" asp-controller="Lesson">
            <div class="card">
                <div class="card-header">
                    <h4>Update Lesson</h4>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Title" class="control-label">Lesson Title</label>
                    <input asp-for="Title" class="form-control" value="@lesson.Title" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <br />
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label asp-for="Course_Id" class="control-label">Course</label>
                        <select asp-for="Course_Id" asp-items="@ViewBag.CourseList" class="form-control">
                         @* <option value="">Please select a course</option> *@
                        @foreach (var course in ViewBag.CourseList as SelectList)
                        {
                            @(lesson.Course_Id.ToString() == course.Value ? "selected" : "")
                            <option value="@course.Value"></option>
                        }
                        </select>
                    </div>
                    <br />
                    <div class="form-group col-md-6">
                        <label asp-for="Content_Name" class="control-label">Content Name</label>
                        <input asp-for="Content_Name" class="form-control" value="@content_name" />
                        <span asp-validation-for="Content_Name" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group col-md-6">
                        <label asp-for="Content_Type" class="control-label">Lesson Type</label>
                        <select asp-for="Content_Type" asp-items="@ViewBag.LessonTypes" class="form-control">
                            <option value="">@lesson_type</option>
                        </select>
                    </div>
                    <br />
                </div>
                <input type="hidden" name="Lesson_Id" value="@lesson.Lesson_Id" />

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Update Lesson</button>
                </div>
            </div>
        </form>
    </div>
</div>
<br />
<p id="alert">
    @ViewBag.Message
</p>

<script>
    // Hide alert after 3 seconds
    setTimeout(function () {
        document.getElementById("alert").style.display = "none";
    }, 3000);
</script>